spring:
  config:
    import: optional:secrets-dev.yaml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
    hibernate:
      SQL: debug
      type:
        descriptor:
          sql:
            BasicBinder: trace
    pro:
      arcodeh:
        msgoba_2002_server:
          security: INFO