spring:
  application:
    name: msgoba-2002-server
  config:
    import: optional:secrets.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  flyway:
    enabled: true
server:
  servlet:
    context-path: /api