ALTER TABLE profile
ALTER COLUMN hobbies TYPE TEXT[];

ALTER TABLE profile
ALTER COLUMN hobbies SET NOT NULL;

ALTER TABLE QUESTION
ALTER COLUMN options TYPE TEXT[];

ALTER TABLE QUESTION
ALTER COLUMN options SET NOT NULL;

